/* interface for a helper used by ipc_suite.c . */

[StubPrefix(__ipchelper)]
interface IpcHelper
{
	[Label(0xdead)]
	oneway void quit();

	/* causes the helper thread to get another scheduling quantum before
	 * returning to play.
	 */
	[Label(0x1233)]
	void yield();

	/* @sleep_after_us provokes the case where send-phase preemption sets a
	 * timeout which is reset on r_recv -> recv_wait.
	 */
	[Label(0x1234), StubSendTimeout, StubRecvTimeout]
	void sleep(
		in long us,			/* µs of sleep */
		in boolean spin,	/* false = IPC sleep, true = spinning */
		in long sleep_after_us);	/* length of IPC sleep after */
};
