
/* hand-generated configuration header. do not commit any version that leaves
 * any variable undefined.
 *
 * this file will eventually be generated by script.
 */

#ifndef SEEN_UKERNEL_CONFIG_H
#define SEEN_UKERNEL_CONFIG_H


/* whether the kernel supports the ia32/amd64 SYSENTER/SYSEXIT mechanism. */
#define CONFIG_X86_SYSENTER 1


/* derived variables. */
#ifdef CONFIG_X86_SYSENTER
#define USE_SYSENTER 1
#else
#define USE_SYSENTER 0
#endif


#endif
